### ISSUE TITLE
Meta Issue: IA Improvements from User Feedback

### ISSUE THREAD

**Issue by pjhampton** [duckduckgo/zeroclickinfo-spice#3162]
## IA Improvements from User Feedback (Spice)

DuckDuckGo has [over 1000 IAs](https://duck.co/ia) in production. Utilizing user feedback, we want to make these IAs even more awesome! Below is a list of tasks that need to be completed for existing IAs. 

#### High Priority
  - [ ] [ExpandURL: Find a better URL expanding API](https://github.com/duckduckgo/zeroclickinfo-spice/issues/3164)
  - [ ] [Github: Search issues](https://github.com/duckduckgo/zeroclickinfo-spice/issues/3170)
  - [ ] [Timer: Timezone Based Searches](https://github.com/duckduckgo/zeroclickinfo-spice/issues/3181)
  - [x] ~~[Geometry: expand trigger space to cover more common queries](https://github.com/duckduckgo/zeroclickinfo-spice/issues/2386)~~ - Thanks to @adityatandon007 
  
#### Low Hanging Fruit
  - [x] ~~[Forecast: Text overlapping with image](https://github.com/duckduckgo/zeroclickinfo-spice/issues/3167)~~
  - [x] ~~[Currency Conversion: Enable Triggering for symbol before amount](https://github.com/duckduckgo/zeroclickinfo-spice/issues/3165)~~
  - [x] ~~[Currency Conversion: RUB aliases needed](https://github.com/duckduckgo/zeroclickinfo-spice/issues/3168)~~

#### Discussion
  - [ ] [Currency Conversion: Not working when spaces are in the amount](https://github.com/duckduckgo/zeroclickinfo-spice/issues/3109)
  - [ ] [Nutrition: Wanted result in specific serving size](https://github.com/duckduckgo/zeroclickinfo-spice/issues/3104)
  - [ ] [GitHub: Not showing for explicit github repo query](https://github.com/duckduckgo/zeroclickinfo-spice/issues/3103)

**Comment by pjhampton** [comment]
Hey @duckduckgo/duckduckhack-contributors! 

Is anybody interested by any of the above issues? 🚀  😄

**Comment by pjhampton** [comment]
Closing for now. If anybody is following this issue, please check out https://duckduckhack.com/issues instead 👍
