### ISSUE TITLE
Package Tracking: Update to ignore queries for ISBN numbers

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#3269]
## Problem

If a query contains "isbn" and contains 10 or 13 numbers, the IA should ignore the query as it is not a valid package tracking code.

## Solution

1. Add some tests for ISBN 10 and ISBN 13 queries, e.g. `isbn 9780134494326 => undef`
2. Update the `handle` function to ignore queries containing `isbn`
3. Send a PR

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---
IA Page:  https://duck.co/ia/view/package_tracking

**Comment by adityatandon007** [comment]
@moollaza can you give me an example on how to recreate this if this is a bug

**Comment by moollaza** [comment]
@adityatandon007 https://duckduckgo.com/?q=isbn+0134494164

If you look in the console we're making a call to `/js/spice/package_tracking`. You can test this in duckpan as well with those queries.

Basically if the query contains `isbn` the package tracking Spice should bail out and not make an API call

**Comment by mayank** [comment]
@moollaza i can give it a try!

**Comment by dpanshuarora** [comment]
Does it not need to make an API call (package tracking) at all if ISBN is present or only when ISBN along with a 10 or 13 digit number is present?

**Comment by pulkitrohan** [comment]
Hi @moollaza,

I want to work on this. Please let me know if I proceed with the work.
