### ISSUE TITLE
PackageTracking: Add regex trigger for OnTrac Pattern

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/zeroclickinfo-spice#3344]
### Description
Currently a search for just an OnTrac parcel number returns no results. We can add a regex trigger for this pattern to capture it though.

As far as I've been able to tell OnTrac package codes are simply a "c" followed by 14 digits: 

```perl
/^c\d{14}$/
```

This regex should be added alongside the others in the Perl code.

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/package_tracking

**Comment by adityatandon007** [comment]
@moollaza  I  can try this 
If I understood the issue do I have to simply add that regex only. how is it gonna find onTrac. Do we have an entry for onTrac in carriers file. Assuming we have an entry for onTrac , I will have to just add that regex trigger. Is it right?
